# ======================================================================================================================
# Execution parameters
# ======================================================================================================================
quiet: True
seed: 125
device: "cpu"
n_epochs: 15000
env_name: "thesis-env-v1"
# ======================================================================================================================
# Parallelization parameters
# ======================================================================================================================
multirunner: True
processes: 8

# ======================================================================================================================
# Testing parameters
# ======================================================================================================================
test_episodes: 50
# ======================================================================================================================
# Model parameters
# ======================================================================================================================
actor_arch: [80, "relu", 80, "relu"]
critic_arch: [80, "relu", 80, "relu"]
max_grad_norm: null # Unused for now
batch_size: 40
train_iters: 50
optimizer_act: "Adam"
lr_act: 1.0e-3
lr_act_min: 1.0e-6
optimizer_crit: "Adam"
lr_crit: 1.0e-2
lr_crit_min: 1.0e-5
lr_decay_step: 200
lr_decay_episode_perc: 0.8
checkpoint_interval: 200

# ======================================================================================================================
# PPO-specific parameters
# ======================================================================================================================
clip_range: 0.2
clip_range_vf: null
normalize_advantage: True
normalize_returns: False
ent_coef: 0.03
vf_coef: 0.01
target_kl: 0.025
lam: 0.95
use_exploration_rate: False
epsilon0: .0
epsilon1: .0

#fork_on: "thread" # "thread" or "process"
# ======================================================================================================================
# Plotting/logging parameters
# ======================================================================================================================
log_enabled: True
log_interval: 200
#test_n_epochs: 50
#test_interval: 20 # set to null to disable testing
# nn
#policy: null # Unused for now
#plot
#enabled: False
#update_interval: 500
# smooth
#smooth_enabled: False
#smooth_n: 11
# Plots to enable
#episode_rewards: True
#total_rewards: True
# log
#save_in_files: False